// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnboardingSIGDB1.Data;

namespace OnboardingSIGDB1.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201006132803_primeiraMigration")]
    partial class primeiraMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnboardingSIGDB1.Domain.Models.Empresa", b =>
                {
                    b.Property<string>("Cnpj")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataFundacao");

                    b.Property<string>("Nome");

                    b.HasKey("Cnpj");

                    b.ToTable("Empresas");
                });
#pragma warning restore 612, 618
        }
    }
}
